repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
  - id: trailing-whitespace
    language_version: python3

- repo: local
  hooks:
  - id: flake8
    name: flake8
    description: Python wemake style guide enforcement
    entry: flake8 --count
    args: ["--config=.flake8"]
    language: python
    types: [python]

- repo: local
  hooks:
  - id: mypy
    name: mypy
    description: Python mypy style guide enforcement
    entry: mypy .
    args: ["--config=pyproject.toml"]
    language: python
    types: [python]

- repo: local
  hooks:
  - id: isort
    name: isort
    description: Python isort
    entry: isort .
    args: ["--config=pyproject.toml"]
    language: python
    types: [python]
