[virtualenvs]
create = true
in-project = true

[tool.poetry]
name = "training-project"
version = "0.1.0"
description = ""
authors = ["alexnazarv <alexnazarv@gmail.com>"]
readme = "README.md"
packages = [{include = "training_project"}]

[tool.poetry.dependencies]
python = "3.10.10"
fastapi = "0.101.0"
uvicorn = {extras = ["standard"], version = "0.23.2"}


[tool.poetry.group.dev.dependencies]
flake8 = "6.1.0"
pep8-naming = "0.13.3"
flake8-bugbear = "23.7.10"
flake8-docstrings = "1.7.0"
flake8-quotes = "3.3.2"
pytest = "7.4.0"
httpx = "0.24.1"
isort = "5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
py_version = 310
line_length = 120
profile = "google"
extend_skip = [".md"]
skip_glob = [".github/*"]
extend_skip_glob = ["Dockerfile"]
skip_gitignore = true
src_paths = ["src", "tests"]

[tool.mypy]
python_version = 3.8
strict = true
follow_imports = "silent"
exclude = "isort/_vendored|tests/unit/example_projects|tests/unit/example_crlf_file.py"

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true
allow_incomplete_defs = true
allow_untyped_calls = true
