# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: syntax check && pytest 

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, merged]
    branches: "**"

permissions:
  contents: read

jobs:
  testing:
  if: ${{ github.event.action }} == 'opened'
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11"]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.5.1"
        
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count
