name: release

on:
  push:
    tags: "**"

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.10.10"
  POETRY_VERSION: "1.5.1"

jobs:
  publish_package:
    if: github.event.inputs.run_manual_job == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install poetry
      run: pipx install poetry==${{ env.POETRY_VERSION }}

    - name: set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'poetry'
    - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: publish to pypi
      run: poetry publish --build
