name: publish_image

on:
  workflow_run:
    workflows: ["tests & lints"]
    branches: ["master", "dev"]
    types:
      - completed
  push:
    branches: ["master", "dev"]
    paths:
      - Dockerfile
      - pyproject.toml
      - poetry.lock
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ vars.GH_TOKEN }}

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    outputs:
      tag: ${{ steps.step_semantic_release.outputs.tag }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: step_semantic_release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


  publish_image:
    if: github.event.inputs.run_manual_job == 'true'
    runs-on: ubuntu-latest
    needs: [semantic_release]

    steps:
    - env:
        TAG: ${{ needs.semantic_release.outputs.tag }}
      run: echo "$TAG"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/training_api:${{ needs.semantic_release.outputs.tag }}
